Set and check a new "user_id" cookie for gameplay
iftechfoundation/ifcomp pull request #262
Opened 2020-09-22 15:57 UTC by jmacdotorg

This work sets a new cookie named "user_id" on login. It contains, blowfish-encrypted and base64-encoded, the current user's database ID.

When someone wishes to play a game outside of the judging season, the app decrypts this cookie (if present) and loads the user with the resulting ID. If that user is allowed to see this game -- that is, they are the game's author, or have "curator" rights to the comp -- then the game will load for them.

This differs from the app's current behavior, which merely checks the ID of the currently logged-in user.

We do this extra work in order to allow games to run on their own subdomains, which purposefully do not have access to the ifcomp.org login-session cookie. We give this new "user_id" cookie access to all ifcomp.org subdomains, so that games running in these walled-off subdomains can perform this check.

This work, plus some additional Apache-level configuration not in version control, fixes #242.

2020-09-22 16:08 UTC, jmacdotorg commented
Coverall is unhappy because the entirety of Plack::Middleware::IFComp is uncovered, and I added a subroutine to it.

This module does need coverage, but that ain't happening today.

2020-09-22 22:36 UTC, mjmusante commented on IFComp/lib/Plack/Middleware/IFComp.pm
> +            warn "And so, the key is " . $self->config->{blowfish_key};
are these lines being left in?

2020-09-22 22:44 UTC, jmacdotorg commented on IFComp/lib/Plack/Middleware/IFComp.pm
> +            warn "And so, the key is " . $self->config->{blowfish_key};
Whoops! Nice catch; lines zapped.

2020-09-22 23:29 UTC, mjmusante approved these changes
looks good to me!

2020-09-23 01:38 UTC, adherzog requested changes
I thought we'd decided to set the expiration date of the cookie to the date the cookie is no longer needed (when the current comp opens for judging, I suppose.)

Can we set the cookie only when it's necessary (when the comp is in whatever phase that requires it.) There's no need to set it for all of the judges once the comp opens for judging.

I don't love the config name of 'blowfish_key' - it's specific to a particular algorithm that might change later, and doesn't actually indicate what the key is for. Maybe something like 'user_id_cookie_key' instead?

Add the config key to the 'ifcomp_local.conf-dist' file, please.

2020-09-23 02:32 UTC, jmacdotorg commented
> I thought we'd decided to set the expiration date of the cookie to the date the cookie is no longer needed (when the current comp opens for judging, I suppose.)
>
> Can we set the cookie only when it's necessary (when the comp is in whatever phase that requires it.) There's no need to set it for all of the judges once the comp opens for judging.

I changed my mind about these, opting to keep things simple and let the new cookie live for exactly as long as the session cookie instead. This way, if someone logs in to judge a game in October, and then enters a game the following summer on the same session, hey, they'll have a functioning user_id cookie without any need to cycle their login.

So I think I'd like to keep these as they are?

> I don't love the config name of 'blowfish_key' - it's specific to a particular algorithm that might change later, and doesn't actually indicate what the key is for. Maybe something like 'user_id_cookie_key' instead?
>
> Add the config key to the 'ifcomp_local.conf-dist' file, please.

Good suggestions; Done and done.

2020-09-24 18:19 UTC, adherzog requested changes
One minor change inline, and then please re-tidy - the CI tests are failing.

Otherwise, looks good to me!

2020-09-24 18:19 UTC, adherzog commented on IFComp/lib/IFComp/Controller/Auth.pm
> +use Crypt::Eksblowfish::Blowfish;
I think this needs to be moved to Controller::Root

2020-09-24 18:35 UTC, adherzog approved these changes

2020-09-24 23:57 UTC, merged